### ISSUE TITLE
Layers from different sources with leaflet 4326

### ISSUE THREAD

**Issue by ramotswa** [nasa-gibs/gibs-web-examples#5]
Hello,
since we are overriding the EPSG def for 4326 in the leaflet example, I am having trouble adding in other layers that otherwise work with just ;
"crs: L.CRS.EPSG4326," in the map definition. Is there a trick to doing this or is there a limitation in leaflet?

Thanks

**Comment by rboller** [comment]
Hi, please take a look at the notes here regarding Leaflet and map projections:
https://github.com/nasa-gibs/gibs-web-examples#leaflet

Otherwise I'm not familiar enough with Leaflet to know what the consequences are when the projection is overridden.  Please reopen this ticket if the above doesn't provide enough information, though, or you suspect there is a problem with the gibs-web-examples code.  Thanks!
